GET http://localhost:5000/products

###
POST http://localhost:5000/products
Content-Type: application/json

{
  "name": "Product 1",
  "description": "Product 1 description",
  "image_url": "https://via.placeholder.com/150",
  "price": 100
}

###
DELETE http://localhost:5000/products/45d368e9-7cb0-48aa-b13b-3275ccbb0882
