GET http://localhost:5000/products

###
POST http://localhost:5000/products
Content-Type: application/json

{
  "name": "Product 3",
  "description": "Product 3 description",
  "image_url": "https://via.placeholder.com/3",
  "price": 300
}

###
DELETE http://localhost:5000/products/45d368e9-7cb0-48aa-b13b-3275ccbb0882

###
GET http://localhost:5000/orders

###
POST http://localhost:5000/orders
Content-Type: application/json

{
  "items": [
    {
      "product_id": "2b47e3b3-dac2-4a30-9ef0-0c6c29474014",
      "quantity": 1
    },
    {
      "product_id": "748bd8dc-efcb-452c-a6d4-9f3c00169ae0",
      "quantity": 2
    }
  ],
  "card_hash": "123"
}
