version: '3.1'

services:
  db:
    image: mysql:8.0.36-debian
    ports:
      - 3306:3306
    restart: always
    environment:
      - MYSQL_DATABASE=nest
      - MYSQL_ROOT_PASSWORD=root

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
