###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "username": "marcos",
  "password": "marcos"
}

###
GET http://localhost:5000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoibWFyY29zIiwiaWF0IjoxNzA2ODI3NjI2LCJleHAiOjE3MDY5MTQwMjZ9.h0uy8HRD1k3UZkHkKS6cX3I0uM9KWRLQ9m9dyKWkW5I

###
POST http://localhost:5000/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoibWFyY29zIiwiaWF0IjoxNzA2ODI3NjI2LCJleHAiOjE3MDY5MTQwMjZ9.h0uy8HRD1k3UZkHkKS6cX3I0uM9KWRLQ9m9dyKWkW5I

{
  "name": "Product 3",
  "description": "Product 3 description",
  "image_url": "https://via.placeholder.com/3",
  "price": 300
}

###
DELETE http://localhost:5000/products/3bbcae40-6378-4398-ad67-931bfd94375c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoibWFyY29zIiwiaWF0IjoxNzA2ODI3NjI2LCJleHAiOjE3MDY5MTQwMjZ9.h0uy8HRD1k3UZkHkKS6cX3I0uM9KWRLQ9m9dyKWkW5I

###
GET http://localhost:5000/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoibWFyY29zIiwiaWF0IjoxNzA2ODI3NjI2LCJleHAiOjE3MDY5MTQwMjZ9.h0uy8HRD1k3UZkHkKS6cX3I0uM9KWRLQ9m9dyKWkW5I

###
POST http://localhost:5000/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoibWFyY29zIiwiaWF0IjoxNzA2ODI3NjI2LCJleHAiOjE3MDY5MTQwMjZ9.h0uy8HRD1k3UZkHkKS6cX3I0uM9KWRLQ9m9dyKWkW5I

{
  "items": [
    {
      "product_id": "2b47e3b3-dac2-4a30-9ef0-0c6c29474014",
      "quantity": 1
    },
    {
      "product_id": "748bd8dc-efcb-452c-a6d4-9f3c00169ae0",
      "quantity": 2
    }
  ],
  "card_hash": "123"
}
