version: '3.8'

services:
  db:
    container_name: 'mysql'
    image: 'mysql:8.0.36-debian'
    ports:
      - 3306:3306
    restart: 'always'
    environment:
      - MYSQL_DATABASE=nest
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    container_name: 'mysql-ui'
    image: 'adminer'
    restart: 'always'
    ports:
      - 8080:8080

  rabbitmq:
    container_name: 'rabbitmq'
    image: 'rabbitmq:3.12-management'
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: 'admin'
      RABBITMQ_DEFAULT_PASS: 'admin'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
  mysql_data:
